name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches: 
    include:
      - "*"
  tags:
    include: 
      - "*"

stages:
# test self-hosted agent
- stage: SelfHostedAgentTest
  pool: 
    name: Default
    vmImage: 'ubuntu-16.04'
  dependsOn: []
  jobs:
  - job: PrintEnv
    displayName: Printenv Job
